### ISSUE TITLE
example hangs in docker compose

### ISSUE THREAD

**Issue by lgarithm** [lgarithm/kumo#5]

**Comment by lgarithm** [comment]
[worker.log](https://github.com/lgarithm/kumo/files/1484327/worker.log)
[master.log](https://github.com/lgarithm/kumo/files/1484328/master.log)

**Comment by lgarithm** [comment]
The first `print` statement right after main is not evaluated (there is no corresponding `write` system call found in strace log).

**Comment by lgarithm** [comment]
It only happens when running with docker-compose.
run `docker run` directly doesn't trigger it.

**Comment by x1957** [comment]
docker-compose bug?

**Comment by lgarithm** [comment]
[docker-compose-traced.log](https://github.com/lgarithm/kumo/files/1484477/docker-compose-traced.log)
[docker-run-traced.log](https://github.com/lgarithm/kumo/files/1484475/docker-run-traced.log)

**Comment by lgarithm** [comment]
comparing the strace logs:
`docker-run-traced.log`
contains
```
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
```
on line 38, while `docker-compose-traced.log` does not.


`docker-run-traced.log`
```
   138	--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=0}} ---
   139	rt_sigreturn({mask=[]})                 = 0
   140	ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
   141	poll([{fd=1, events=POLLOUT}], 1, 0)    = 1 ([{fd=1, revents=POLLOUT}])
   142	write(1, "\"main\"\n", 7"main"
   143	)               = 7
   144	brk(0x1e0c000)                          = 0x1e0c000
   145	brk(0x1e04000)                          = 0x1e04000
   146	open("/etc/gai.conf", O_RDONLY|O_CLOEXEC) = 3
```

`docker-compose-traced.log`
```
   137	ioctl(1, TCGETS, 0x7ffdcbd0c0a0)        = -1 ENOTTY (Inappropriate ioctl for device)
   138	brk(0x2212000)                          = 0x2212000
   139	brk(0x220a000)                          = 0x220a000
   140	open("/etc/gai.conf", O_RDONLY|O_CLOEXEC) = 3
```

**Comment by lgarithm** [comment]
@x1957 the images used were same, difference should be caused by the signals the binaries received.

**Comment by lgarithm** [comment]
SIGWINCH
The SIGWINCH signal is sent to a process when its controlling terminal changes its size (a window change).

**Comment by lgarithm** [comment]
in fact this can be re-produced by a simple hello world program in c
```
#include <stdio.h>

int main() {
  int n = 100;
  int i;
  for (i = 0; i < n; ++i) {
    puts("main");
  }
  char line[1000];
  FILE *fp = fopen("/debug/input", "r"); // mkfifo /debug/input
  fgets(line, 100, fp);
  return 0;
}
```

**Comment by lgarithm** [comment]
docker run sets 
`TERM=xterm`
while docker-compose doesn't

`docker run `
```
execve("/debug/a.out", ["/debug/a.out"], [/* 4 vars */]) = 0
...
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
brk(NULL)                               = 0x55d76cf3e000
brk(0x55d76cf5f000)                     = 0x55d76cf5f000
write(1, "main\n", 5main
)                   = 5
open("/debug/input", O_RDONLY)          = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
```

`docker-compose`
```
execve("/debug/a.out", ["/debug/a.out"], [/* 3 vars */]) = 0
...
fstat(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
brk(NULL)                               = 0x5573f8bf1000
brk(0x5573f8c13000)                     = 0x5573f8c13000
```

**Comment by lgarithm** [comment]
This might related to 
* https://github.com/docker/compose/issues/1506
* https://github.com/docker/compose/issues/5207

**Comment by lgarithm** [comment]
https://stackoverflow.com/questions/6214629/stdout-and-need-to-flush-it-c

**Comment by lgarithm** [comment]
APUE § 5.4

ISO C requires the following buffering characteristics.

* Standard input and standard output are fully buffered, if and only if they do not refer to an interactive device.
* Standard error is never fully buffered.

This, however, doesn't tell us whether standard input and standard output can be unbuffered or line buffered if they refer to an interactive device and whether standard error should be unbuffered or line buffered. Most implementations default to the following types of buffering.
    
* Standard error is always unbuffered.
* All other streams are line buffered if they refer to a terminal device; otherwise, they are fully buffered.
The four platforms discussed in this book follow these conventions for standard I/O buffering: standard error is unbuffered, streams open to terminal devices are line buffered, and all other streams are fully buffered.
